### ISSUE TITLE
修改pspace的值控制器大小不变，只有间距变化

### ISSUE THREAD

**Issue by dpj514** [hizzgdev/jsmind#117]
![qq 20180201112001](https://user-images.githubusercontent.com/25075646/35659601-142091e8-0742-11e8-868c-55e04f0f21a3.png)

**Comment by hizzgdev** [comment]
是的，【pspace】这个参数实际上指的是为控制器预留的空间大小（文档已更新：[commit][1]），要想调整控制器大小，还需要修改 jmexpander 的样式：

```css
jmnodes jmexpander{
    width:28px;
    height:28px;
    line-height:29px;
    font-size:30px;
    ....
}
```
或添加自定义样式（推荐）：
```css
jmnodes.some-theme jmexpander{
......
}
```

[1]: https://github.com/hizzgdev/jsmind/commit/323916513d38469820430f77e91119d062c15a4f
